var sampleData = ["/type/object/name\t/type/object/type\t/film/film/directed_by",
"Stolen Kisses\t/film/film\tFran\u00E7ois Truffaut",
"The Stoned Age\t/film/film\tJames Melkonian",
"Stonewall\t/film/film\tNigel Finch",
"Strange Days\t/film/film\tKathryn Bigelow",
"The Strange Love of Martha Ivers\t/film/film\tLewis Milestone",
"Straw Dogs\t/film/film\tSam Peckinpah",
"A Streetcar Named Desire\t/film/film\tElia Kazan",
"Stripes\t/film/film\tIvan Reitman",
"Stroker Ace\t/film/film\tHal Needham",
"Summertime\t/film/film\tDavid Lean",
"Sunday in the Country\t/film/film\tBertrand Tavernier",
"Surviving the Game\t/film/film\tErnest R. Dickerson",
"Swashbuckler\t/film/film\tJames Goldstone",
"Sweet Dreams\t/film/film\tKarel Reisz",
"Swingers\t/film/film\tDoug Liman",
"Hard Eight\t/film/film\tPaul Thomas Anderson",
"Take the Money and Run\t/film/film\tWoody Allen",
"Tale of Two Sisters\t/film/film\tAdam Rifkin",
"Tales from the Crypt: Demon Knight\t/film/film\tErnest R. Dickerson",
"Tampopo\t/film/film\tJuzo Itami",
"Tango & Cash\t/film/film\tAndrei Konchalovsky",
"Tequila Sunrise\t/film/film\tRobert Towne",
"The Terminator\t/film/film\tJames Cameron",
"Terror of Mechagodzilla\t/film/film\tIshir\u00F4 Honda",
"Tess of the Storm Country\t/film/film\tJohn S. Robertson",
"Tetsuo 2: Body Hammer\t/film/film\tShinya Tsukamoto",
"Tetsuo: The Iron Man\t/film/film\tShinya Tsukamoto",
"They Might Be Giants\t/film/film\tAnthony Harvey",
"The Thief of Bagdad\t/film/film\tRaoul Walsh",
"The Thing\t/film/film\tJohn Carpenter",
"Things to Do in Denver When You\'re Dead\t/film/film\tGary Fleder",
"This Sporting Life\t/film/film\tLindsay Anderson",
"The Thomas Crown Affair\t/film/film\tNorman Jewison",
"Three Amigos\t/film/film\tJohn Landis",
"Three Days of the Condor\t/film/film\tSydney Pollack",
"The Three Musketeers\t/film/film\tStephen Herek",
"Thunder Road\t/film/film\tRobert Mitchum",
"Thunderball\t/film/film\tTerence Young",
"Thunderheart\t/film/film\tMichael Apted",
"Tiger Bay\t/film/film\tJ. Lee Thompson",
"Tim\t/film/film\tMichael Pate",
"Timecop\t/film/film\tPeter Hyams",
"Tin Cup\t/film/film\tRon Shelton",
"The Tingler\t/film/film\tWilliam Castle",
"To Die For\t/film/film\tGus Van Sant",
"Tokyo Fist\t/film/film\tShinya Tsukamoto",
"Tol\'able David\t/film/film\tHenry King",
"Tora! Tora! Tora!\t/film/film\tKinji Fukasuka",
"Tornado!\t/film/film\tNoel Nosseck",
"Tourist Trap\t/film/film\t",
"The Toxic Avenger\t/film/film\tLloyd Kaufman",
"Trancers\t/film/film\tCharles Band",
"La Traviata\t/film/film\tFranco Zeffirelli",
"Trial\t/film/film\tDavid Jones",
"True Grit\t/film/film\tHenry Hathaway",
"True Romance\t/film/film\tTony Scott",
"Truman\t/film/film\tFrank Pierson",
"Madonna: Truth or Dare\t/film/film\tAlek Keshishian",
"The Tune\t/film/film\tBill Plympton",
"Turbulence\t/film/film\tTobert Butler",
"Two Lost Worlds\t/film/film\t",
"Two-Minute Warning\t/film/film\tLarry Peerce",
"Two Moon Junction\t/film/film\tZalman King",
"Two-Lane Blacktop\t/film/film\tMonte Hellman",
"U2: Rattle and Hum\t/film/film\tPhil Joanou",
"The Umbrellas of Cherbourg\t/film/film\tJacques Demy",
"Uncle Buck\t/film/film\tJohn Hughes",
"Under Siege\t/film/film\tAndrew Davis",
"The Underneath\t/film/film\tSteven Soderbergh",
"Vagabond\t/film/film\tAgn\u00E8s Varda",
"The Vanishing\t/film/film\tGeorge Sluizer",
"Vengeance Valley\t/film/film\tRichard Thorpe",
"Very Natural Thing\t/film/film\tChristopher Larkin",
"Victory\t/film/film\tJohn Huston",
"Vive L\'Amour\t/film/film\tMing-liang Tsai",
"Volunteers\t/film/film\tNicholas Meyer",
"Voodoo Dawn\t/film/film\tAndrzej Sekula",
"Waiting to Exhale\t/film/film\tForest Whitaker",
"Walkabout\t/film/film\tNicolas Roeg",
"Walking Tall\t/film/film\tPhil Karlson",
"The War Room\t/film/film\tD.A. Pennebaker",
"The War Wagon\t/film/film\tBurt Kennedy",
"Wedding Bell Blues\t/film/film\tDana Lustig",
"The Westerner\t/film/film\tWilliam Wyler",
"When a Man Loves a Woman\t/film/film\tLuis Mandoki",
"When We Were Kings\t/film/film\tLeon Gast",
"Where the Buffalo Roam\t/film/film\tArt Linson",
"White Palace\t/film/film\tLuis Mandoki",
"White Squall\t/film/film\tRidley Scott",
"Who\'s Afraid of Virginia Woolf?\t/film/film\tMike Nichols",
"Wide Awake\t/film/film\tM. Night Shyamalan",
"The Wild One\t/film/film\tLaslo Benedek",
"The Winslow Boy\t/film/film\tDavid Mamet",
"Winstanley\t/film/film\tAndrew Mollo",
"Witness\t/film/film\tPeter Weir",
"The Woman Who Came Back\t/film/film\tWalter Colmes",
"Women in Revolt\t/film/film\tPaul Morrissey",
"Wrecking Crew\t/film/film\t",
"Xanadu\t/film/film\tRobert Greenwald",
"Year of the Gun\t/film/film\tJohn Frankenheimer",
"Yellow Submarine\t/film/film\tGeorge Dunning",
"Yojimbo\t/film/film\tAkira Kurosawa",
"Young Guns II\t/film/film\tGeoff Murphy",
"Zu: Warriors from the Magic Mountain\t/film/film\tHark Tsui",
"Gridlock\'d\t/film/film\tVondie Curtis-Hall",
"Shanghai Grand\t/film/film\tPoon Man Kit",
"The House of Yes\t/film/film\tMark S. Waters",
"Love Jones\t/film/film\tTheodore Witcher",
"Clockwatchers\t/film/film\tJill Sprecher",
"Zeus and Roxanne\t/film/film\tGeorge Miller",
"Meet Wally Sparks\t/film/film\tPeter Baldwin",
"Chasing Amy\t/film/film\tKevin Smith",
"Absolute Power\t/film/film\tClint Eastwood",
"Dante\'s Peak\t/film/film\tRoger Donaldson",
"Hugo Pool\t/film/film\tRobert Downey Sr.",
"Rosewood\t/film/film\tJohn Singleton",
"Fools Rush In\t/film/film\tAndy Tennant",
"Vegas Vacation\t/film/film\tStephen Kessler",
"The Three Stooges: Sing a Song of Six Pants\t/film/film\tJules White",
"Quatermass and the Pit\t/film/film\tRoy Ward Baker",
"The Bicycle Thief\t/film/film\tVittorio De Sica",
"For a Few Dollars More\t/film/film\tSergio Leone",
"Mean Guns\t/film/film\tAlbert Pyun",
"Samurai Trilogy 2: Duel at Ichijoji Temple\t/film/film\tHiroshi Inagaki",
"Head: The Monkees\t/film/film\tBob Rafelson",
"Private Parts\t/film/film\tBetty Thomas",
"Boys Life 2\t/film/film\tNickolas Perry",
"The Designated Mourner\t/film/film\tDavid Hare",
"Selena\t/film/film\tGregory Nava",
"The Devil\'s Own\t/film/film\tAlan J. Pakula",
"Grosse Pointe Blank\t/film/film\tGeorge Armitage",
"Double Team\t/film/film\tHark Tsui",
"Anaconda\t/film/film\tLuis Llosa",
"Murder at 1600\t/film/film\tDwight H. Little",
"Volcano\t/film/film\tMick Jackson",
"Austin Powers: International Man of Mystery\t/film/film\tJay Roach",
"Warriors of Virtue\t/film/film\tRonny Yu",
"Fathers\' Day\t/film/film\tIvan Reitman",
"The Bride with White Hair\t/film/film\tRonny Yu",
"Hard Rain\t/film/film\tMichael Salomon",
"Batman & Robin\t/film/film\tJoel Schumacher",
"Face/Off\t/film/film\tJohn Woo",
"Speed 2: Cruise Control\t/film/film\tJan De Bont",
"My Son the Fanatic\t/film/film\tUdayan Prasad",
"Pretty Village, Pretty Flame\t/film/film\tSrdjan Dragojevic",
"Africa: The Serengeti: IMAX\t/film/film\tGeorge Casey",
"Beware! Children at Play\t/film/film\tMik Cribben",
"Insomnia\t/film/film\tErik Skjoldbjaerg",
"The Sweet Hereafter\t/film/film\tAtom Egoyan",
"Ma Vie En Rose\t/film/film\tAlain Berliner",
"Taste of Cherry\t/film/film\tAbbas Kiarostami",
"Mrs. Brown\t/film/film\tJohn Madden",
"Armageddon\t/film/film\tGordon Chan",
"Last Breath\t/film/film\tPJ Posner",
"Till the Clouds Roll By\t/film/film\tVincente Minnelli",
"Jack-O\t/film/film\tSteve Latshaw",
"Hercules\t/film/film\tRon Clements",
"George of the Jungle\t/film/film\tSam Weisman",
"Contact\t/film/film\tRobert Zemeckis",
"Nothing to Lose\t/film/film\tSteve Oedekerk",
"Air Force One\t/film/film\tWolfgang Petersen",
"Conspiracy Theory\t/film/film\tRichard Donner",
"Air Bud\t/film/film\tCharles Martin Smith",
"Soul Food\t/film/film\tGeorge Tillman Jr.",
"In & Out\t/film/film\tFrank Oz",
"The Game\t/film/film\tDavid Fincher",
"Kull the Conqueror\t/film/film\tJohn Nicolella",
"How To Be A Player\t/film/film\tLionel C. Martin",
"A Life Less Ordinary\t/film/film\tDanny Boyle",
"Deconstructing Harry\t/film/film\tWoody Allen",
"Hoodlum\t/film/film\tBill Duke",
"Lawn Dogs\t/film/film\tJohn Duigan",
"The Apostle\t/film/film\tRobert Duvall",
"Gattaca\t/film/film\tAndrew Niccol",
"The Spanish Prisoner\t/film/film\tDavid Mamet",
"Swept from the Sea\t/film/film\tBeeban Kidron",
"Telling Lies in America\t/film/film\t",
"The Real Blonde\t/film/film\tTom DiCillo",
"Six Ways to Sunday\t/film/film\tAdam Bernstein",
"The Ugly\t/film/film\tScott Reynolds",
"Playing God\t/film/film\tAndy Wilson",
"Dancehall Queen\t/film/film\tRick Elgood",
"Desperate Measures\t/film/film\tBarbet Schroeder",
"Home Alone 3\t/film/film\tRaja Gosnell",
"Mouse Hunt\t/film/film\tGore Verbinski",
"As Good as It Gets\t/film/film\tJames L. Brooks",
"The Postman\t/film/film\tKevin Costner",
"The Big Lebowski\t/film/film\tJoel Coen",
"Midnight in the Garden of Good and Evil\t/film/film\tClint Eastwood",
"Scream 2\t/film/film\tWes Craven",
"Mortal Kombat: Annihilation\t/film/film\tJohn R. Leonetti",
"An American Werewolf in Paris\t/film/film\tJohn Landis",
"The Gingerbread Man\t/film/film\tRobert Altman",
"I Know What You Did Last Summer\t/film/film\tJim Gillespie",
"The Devil\'s Advocate\t/film/film\tTaylor Hackford",
"Switchback\t/film/film\tJeb Stuart",
"I Love You, I Love You Not\t/film/film\tBilly Hopkins",
"Broken Vessels\t/film/film\tScott Ziehl",
"Godzilla\t/film/film\tRoland Emmerich",
"Happiness\t/film/film\tTodd Solondz",
"Like It Is\t/film/film\tPaul Oremland",
"A Perfect Murder\t/film/film\tAndrew Davis",
"The Dreamlife of Angels\t/film/film\tErick Zonca",
"Chemmeen: Malayalam\t/film/film\tRamu Kariat",
"Upkar\t/film/film\tManoj Kumar",
"Anastasia\t/film/film\tGary Goldman",
"The Borrowers\t/film/film\tPeter Hewitt",
"Trekkies\t/film/film\tRoger Nygard",
"Incognito\t/film/film\tJohn Badham",
"Spice World\t/film/film\tBob Spiers",
"Firestorm\t/film/film\tDean Semler",
"Fallen\t/film/film\tGregory Hoblit",
"Sliding Doors\t/film/film\tPeter Howitt",
"Pi: Faith in Chaos\t/film/film\tDarren Aronofsky",
"Gods and Monsters\t/film/film\tBill Condon",
"Polish Wedding\t/film/film\tTheresa Connelly",
"Kurt & Courtney\t/film/film\tNick Broomfield",
"Lee Rock\t/film/film\tLawrence Ah Mon",
"God of Gamblers Return\t/film/film\tJing Wong",
"Lawyer Lawyer\t/film/film\tJoe Ma",
"Species II\t/film/film\tPeter Medak",
"In God\'s Hands\t/film/film\tZalman King",
"The Big Hit\t/film/film\tKirk Wong",
"Cannibal! The Musical\t/film/film\tTrey Parker",
"Shivers\t/film/film\tDavid Cronenberg",
"Meet John Doe\t/film/film\tFrank Capra",
"Six Days, Seven Nights\t/film/film\tIvan Reitman",
"The X-Files: Fight the Future\t/film/film\tRob Bowman",
"Dr. Dolittle\t/film/film\tBetty Thomas",
"Southie\t/film/film\tJohn Shea",
"Spawn 2\t/film/film\tEric Radomski",
"Cats\t/film/film\tDavid Mallet",
"Phoenix\t/film/film\tDanny Cannon",
"Curse of the Puppet Master\t/film/film\tVictoria Sloan",
"Mafia!\t/film/film\tJim Abrahams",
"Disturbing Behavior\t/film/film\tDavid Nutter",
"BASEketball\t/film/film\tDavid Zucker",
"Ever After: A Cinderella Story\t/film/film\tAndy Tennant",
"Madeline\t/film/film\tDaisy Von Scherler Mayer",
"Your Friends & Neighbors\t/film/film\tNeil LaBute",
"How Stella Got Her Groove Back\t/film/film\tKevin Rodney Sullivan",
"Why Do Fools Fall in Love\t/film/film\tGregory Nava",
"Man with the Movie Camera\t/film/film\tDziga Vertov",
"When Trumpets Fade\t/film/film\tJohn Irvin",
"Tomorrow Never Dies\t/film/film\tRoger Spottiswoode",
"Posse\t/film/film\tMario Van Peebles",
"Flesh for Frankenstein\t/film/film\tPaul Morrissey",
"Blood for Dracula\t/film/film\tAntonio Margheriti",
"Aflatoon\t/film/film\tGuddu Dhanoa",
"Fearless Hyena 1 / Fearless Hyena 2\t/film/film\t",
"Dark Star\t/film/film\tJohn Carpenter",
"Hitman\t/film/film\tTung Wai",
"Beast Cops\t/film/film\tDante Lam",
"The Wonderful, Horrible Life of Leni Riefenstahl\t/film/film\tRay Muller",
"Lethal Weapon 4\t/film/film\tRichard Donner",
"Tekken\t/film/film\tJunji Sakamoto",
"The Lost World\t/film/film\tHarry O. Hoyt",
"Nothing Sacred\t/film/film\tWilliam A. Wellman",
"Odin: Photon Space Sailer Starlight\t/film/film\tEichi Yamamoto",
"Another Day in Paradise\t/film/film\tLarry Clark",
"Antz\t/film/film\tEric Darnell",
"Besieged\t/film/film\tBernardo Bertolucci",
"Clay Pigeons\t/film/film\tDavid Dobkin",
"Elizabeth\t/film/film\tShekhar Kapur",
"Get Real\t/film/film\tSimon Shore",
"Hilary and Jackie\t/film/film\tAnand Tucker",
"Home Fries\t/film/film\tDean Parisot",
"Hurlyburly\t/film/film\tAnthony Drazan",
"One True Thing\t/film/film\tCarl Franklin",
"Rushmore\t/film/film\tWes Anderson",
"Urban Legend\t/film/film\tJamie Blanks",
"Very Bad Things\t/film/film\t",
"Amir Garib\t/film/film\tMohan Kumar",
"Zanjeer\t/film/film\tPrakash Mehra",
"Jack Frost\t/film/film\tMichael Cooney",
"The Big Chill\t/film/film\tLawrence Kasdan",
"Bulworth\t/film/film\tWarren Beatty",
"The Long Good Friday\t/film/film\tJohn Mackenzie",
"Koyla\t/film/film\tRakesh Roshan",
"Gupt\t/film/film\tRajiv Rai",
"Sholay\t/film/film\tRamesh Sippy",
"Virasat\t/film/film\tPriyadarshan",
"Ishq\t/film/film\tIndra Kumar",
"Raja Hindustani\t/film/film\t",
"Yes Boss\t/film/film\tAziz Mirza",
"Karan Arjun\t/film/film\tRakesh Roshan",
"Kasme Vaade\t/film/film\tRamesh Bhel",
"Mrityudand\t/film/film\tPrakash Jha",
"Saat Rang Ke Sapne\t/film/film\tPriyadarshan",
"Dil Se\t/film/film\tMani Ratnam",
"Lola Montes\t/film/film\tMax Ophuls",
"Jackie Chan\'s First Strike\t/film/film\tStanley Tong",
"The River Wild\t/film/film\tCurtis Hanson",
"Waterworld\t/film/film\tKevin Reynolds",
"12 Monkeys\t/film/film\tTerry Gilliam",
"Time Bandits\t/film/film\tTerry Gilliam",
"Ronin\t/film/film\tJohn Frankenheimer",
"Winners & Sinners\t/film/film\tSammo Hung Kam-Bo",
"Wild Search\t/film/film\tRingo Lam",
"Namak Haraam\t/film/film\tHrishikesh Mukherjee",
"Tridev\t/film/film\tRajiv Rai",
"Tere Mere Sapne\t/film/film\tJoy Augustine",
"My Life as a Dog\t/film/film\tLasse Hallstr\u00F6m",
"Ringmaster\t/film/film\tNeil Abramson",
"Jai Santoshi Maa\t/film/film\tVijay Sharma",
"True Stories\t/film/film\tDavid Byrne",
"Living Out Loud\t/film/film\tRichard LaGravenese",
"Sargam\t/film/film\tK. Vishwanath",
"Millionaire\'s Express\t/film/film\tSammo Hung Kam-Bo",
"Mighty Joe Young\t/film/film\tRon Underwood",
"Custer of the West\t/film/film\tRobert Siodmak",
"I Still Know What You Did Last Summer\t/film/film\tDanny Cannon",
"Legionnaire\t/film/film\tPeter McDonald",
"Ram Balram\t/film/film\tVijay Anand",
"The Rugrats Movie\t/film/film\tIgor Kovalyov",
"Six-String Samurai\t/film/film\tLance Mungia",
"A Bug\'s Life\t/film/film\tAndrew Stanton",
"Dil\t/film/film\tIndra Kumar",
"Things to Come\t/film/film\tWilliam Cameron Menzies",
"Celebrity\t/film/film\tWoody Allen",
"What Dreams May Come\t/film/film\tVincent Ward",
"Razor Blade Smile\t/film/film\tJake West",
"Holy Man\t/film/film\tStephen Herek",
"Just Write\t/film/film\tAndrew Gallerani",
"Finding Graceland\t/film/film\tDavid Winkler",
"Little Voice\t/film/film\tMark Herman",
"Enemy of the State\t/film/film\tTony Scott",
"Babe: Pig in the City\t/film/film\tGeorge Miller",
"Psycho\t/film/film\tGus Van Sant",
"Still Crazy\t/film/film\tBrian Gibson",
"Brown\'s Requiem\t/film/film\tJason Freeland",
"You\'ve Got Mail\t/film/film\tNora Ephron",
"A Civil Action\t/film/film\tSteven Zaillian",
"The Faculty\t/film/film\tRobert Rodriguez",
"At First Sight\t/film/film\tIrwin Winkler",
"In Dreams\t/film/film\tNeil Jordan",
"Gloria\t/film/film\tSidney Lumet",
"Romance\t/film/film\tCatherine Breillat",
"Blast from the Past\t/film/film\tHugh Wilson",
"Buena Vista Social Club\t/film/film\tWim Wenders",
"Better Than Chocolate\t/film/film\tAnne Wheeler",
"Out of Sight\t/film/film\tSteven Soderbergh",
"Sci-Fighters\t/film/film\tPeter Svatek",
"Texas Chainsaw Massacre: The Next Generation\t/film/film\tKim Henkel",
"Gangster World\t/film/film\t",
"She\'s All That\t/film/film\tRobert Iscove",
"From Dusk Till Dawn 2: Texas Blood Money\t/film/film\tScott Spiegel",
"Bloodsport 4\t/film/film\tElvis Restaino",
"Simply Irresistible\t/film/film\tMark Tarlov",
"October Sky\t/film/film\tJoe Johnston",
"Existenz\t/film/film\tDavid Cronenberg",
"8MM\t/film/film\tJoel Schumacher",
"Just the Ticket\t/film/film\tRichard Wenk",
"Analyze This\t/film/film\tHarold Ramis",
"The Corruptor\t/film/film\tJames Foley",
"The Rage: Carrie 2\t/film/film\tKatt Shea",
"Turbulence\t/film/film\tJon McCormack",
"The King and I\t/film/film\tRichard Rich",
"The Boxer\t/film/film\tJim Sheridan",
"Bonnie and Clyde\t/film/film\tArthur Penn",
"Hum Aapke Dil Mein Rehte Hain\t/film/film\tSatish Kaushik",
"The Patriot\t/film/film\tDean Semler",
"I, Zombie\t/film/film\tAndrew Parkinson",
"Jawbreaker\t/film/film\tDarren Stein",
"Storm of the Century\t/film/film\tCraig R. Baxley",
"The Arrival / The Arrival 2\t/film/film\tDavid Twohy",
"Roja\t/film/film\tMani Ratnam",
"Double Platinum\t/film/film\tRobert Allan Ackerman",
"Zakhm\t/film/film\tMahesh Bhatt",
"Aa Ab Laut Chalen\t/film/film\tRishi Kapoor",
"Ghayal\t/film/film\tRaj Kumar Santoshi",
"Pyaar To Hona Hi Tha\t/film/film\tAnees Bazmee",
"Chachi 420\t/film/film\tKamal Hassan",
"Jeans\t/film/film\tShankar",
"Khamoshi\t/film/film\tSanjay Leela Bhansali",
"Paulie\t/film/film\tJohn Roberts",
"Aadmi\t/film/film\tA. Bheem Singh",
"Beta\t/film/film\tIndra Kumar",
"Anarkali\t/film/film\tNandlal Jaswantlal",
"Aandhi\t/film/film\tGulzar",
"Chandni\t/film/film\tYash Chopra",
"Agni Sakshi\t/film/film\tParto Ghosh",
"Chupke Chupke\t/film/film\tHrishikesh Mukherjee",
"Hero\t/film/film\tSubhash Ghai",
"Hero No. 1\t/film/film\tDavid Dhawan",
"Kaun\t/film/film\tRam Gopal Varma",
"Professor\t/film/film\tLekh Tandon",
"Aaina\t/film/film\tYash Chopra",
"Army\t/film/film\tRaam Shetty",
"Umrao Jaan\t/film/film\tMuzaffar Ali",
"The Witches\t/film/film\tNicolas Roeg",
"Ready to Wear\t/film/film\tRobert Altman",
"Cat City\t/film/film\tBela Ternovsky",
"Office Space\t/film/film\tMike Judge",
"Antonia\'s Line\t/film/film\tMarleen Gorris",
"Idle Hands\t/film/film\tRodman Flender",
"Love Story\t/film/film\tRajendra Kumar",
"The \'Burbs\t/film/film\tJoe Dante",
"The Mod Squad\t/film/film\tScott Silver",
"Forces of Nature\t/film/film\tBronwen Hughes",
"The Out-of-Towners\t/film/film\tSam Weisman",
"Ravenous\t/film/film\tAntonia Bird",
"The Mummy\t/film/film\tStephen Sommers",
"Pushing Tin\t/film/film\tMike Newell",
"1941\t/film/film\tSteven Spielberg",
"1942: A Love Story\t/film/film\tVidhu Vinod Chopra",
"April 1st Vidudhala\t/film/film\tVamsy",
"Cobra\t/film/film\tJoseph Henabery",
"Army of One\t/film/film\tVic Armstrong",
"Jeene Ki Raah\t/film/film\tL.V. Prasad",
"C.I.D.\t/film/film\tRaj Khosla",
"Darr\t/film/film\tYash Chopra",
"Iron Monkey\t/film/film\t",
"Saagar\t/film/film\tRamesh Sippy",
"Shahenshah\t/film/film\tTinnu Anand",
"Trimurti\t/film/film\tMukul Anand",
"Vidhaata\t/film/film\tSubhash Ghai",
"Zindagi Ek Juaa\t/film/film\tPrakash Mehra",
"Anupama\t/film/film\tHrishikesh Mukherjee",
"Dil Hai Ke Manta Nahin\t/film/film\tMahesh Bhatt",
"English Babu Desi Mem\t/film/film\tPraveen Nischol",
"Hera Pheri\t/film/film\tPrakash Mehra",
"Jhanak Jhanak Payal Baaje\t/film/film\tV. Shantaram",
"Parinda\t/film/film\tVidhu Vinod Chopra",
"Trinity and Beyond: Atomic Bomb\t/film/film\tPeter Kuran",
"The Confession\t/film/film\tDavid Jones",
"Urban Menace\t/film/film\tAlbert Pyun",
"20,000 Leagues Under the Sea\t/film/film\tStuart Paton",
"2010: The Year We Make Contact\t/film/film\tPeter Hyams",
"Operation Condor 2: Armour of the Gods\t/film/film\tJackie Chan",
"Marlene\t/film/film\tMaximilian Schell",
"Atomic Train\t/film/film\tDick Lowry",
"36 Fillette\t/film/film\tCatherine Breillat",
"48 Hrs.\t/film/film\tWalter Hill",
"Akele Hum Akele Tum\t/film/film\tMansoor Khan",
"Disco Dancer\t/film/film\tB. Subhash",
"Gol Maal\t/film/film\tHrishikesh Mukherjee",
"Hum Kisise Kum Nahim\t/film/film\tNasir Hussain",
"Kaagaz Ke Phool\t/film/film\tGuru Dutt",
"10 Things I Hate About You\t/film/film\tGil Junger",
"Life\t/film/film\tTed Demme",
"Never Been Kissed\t/film/film\tRaja Gosnell",
"Hello Brother\t/film/film\tSohail Khan",
"Hote Hote Pyaar Ho Gaya\t/film/film\tFiroz Irani",
"Warlock 3: The End of Innocence\t/film/film\tEric Freiser",
"Austin Powers: The Spy Who Shagged Me\t/film/film\tJay Roach",
"Instinct\t/film/film\tJon Turtletaub",
"The Thirteenth Floor\t/film/film\tJosef Rusnak",
"Children of the Corn 666: Isaac\'s Return\t/film/film\tKari Skogland",
"Above the Law\t/film/film\tAndrew Davis",
"Absence of Malice\t/film/film\tSydney Pollack",
"Fitzcarraldo\t/film/film\tWerner Herzog",
"Hum Dil De Chuke Sanam\t/film/film\tSanjay Leela Bhansali",
"Pink Floyd: The Wall\t/film/film\tAlan Parker",
"Salaakhen\t/film/film\t",
"Metallica: Cliff \'Em All\t/film/film\tJean Pellerin",
"Metallica: A Year and a Half in the Life of Metallica #1\t/film/film\tAdam Dubin",
"Yudh\t/film/film\t",
"The Addams Family\t/film/film\tBarry Sonnenfeld",
"Addicted to Love\t/film/film\tGriffin Dunne",
"The General\t/film/film\tBuster Keaton",
"Sakura Wars\t/film/film\t",
"Friends & Lovers\t/film/film\tGeorge Haas",
"Resurrection\t/film/film\tRussell Mulcahy",
"Saving Private Ryan\t/film/film\tSteven Spielberg",
"Bartok the Magnificent\t/film/film\tDon Bluth",
"Grand Illusion\t/film/film\tJean Renoir",
"Puppet Master\t/film/film\tDavid Schmoeller",
"The Adventures of Baron Munchausen\t/film/film\tTerry Gilliam",
"Entrapment\t/film/film\tJon Amiel",
"Heavy Metal\t/film/film\tGerald Potterton",
"Drop Dead Gorgeous\t/film/film\tMichael Patrick Jann",
"American Pie\t/film/film\tPaul Weitz",
"Teaching Mrs. Tingle\t/film/film\tKevin Williamson",
"Summer of Sam\t/film/film\tSpike Lee",
"GoldenEye\t/film/film\tMartin Campbell",
"Death Rides a Horse\t/film/film\tGiulio Petroni",
"Darkside Blues\t/film/film\t",
"The Love Letter\t/film/film\tPeter Ho-Sun Chan",
"Killer Condom\t/film/film\tMartin Walz",
"Led Zeppelin: The Song Remains the Same\t/film/film\tJoe Massot",
"The Adventures of Pinocchio\t/film/film\tSteve Barron",
"Boiling Point\t/film/film\t\"Takeshi \"\"Beat\"\" Kitano\"",
"Everest: IMAX\t/film/film\tGreg Mac Gillivray",
"Top of the World\t/film/film\tSidney J. Furie",
"Trippin\'\t/film/film\tDavid Raynr",
"Black Sunday\t/film/film\tMario Bava",
"Corrina, Corrina\t/film/film\tJessie Nelson",
"The General\'s Daughter\t/film/film\tSimon West",
"Now and Then\t/film/film\tLesli Linka Glatter",
"Rogue Trader\t/film/film\tJames Dearden",
"Run Lola Run\t/film/film\tTom Tykwer",
"Lake Placid\t/film/film\tSteve Miner",
"Great Expectations\t/film/film\tAlfonso Cuar\u00F3n",
"The Thomas Crown Affair\t/film/film\tJohn McTiernan",
"Wind in the Willows\t/film/film\t",
"Aaye Din Bahaar Ke\t/film/film\tRaghunath Jhalani",
"Desh Premee\t/film/film\tManmohan Desai",
"Henna\t/film/film\t",
"Hindustan Ki Kasam\t/film/film\tVeeru Devgan",
"Purab Aur Pachhim\t/film/film\t",
"Vaastav\t/film/film\t",
"Clean, Shaven\t/film/film\tLodge Kerrigan",
"Universal Soldier: The Return\t/film/film\tMic Rodgers",
"Dudley Do-Right\t/film/film\tHugh Wilson",
"Stir of Echoes\t/film/film\tDavid Koepp",
"Limbo\t/film/film\tJohn Sayles",
"An Affair to Remember\t/film/film\tLeo McCarey",
"Against All Odds\t/film/film\tTaylor Hackford",
"Air America\t/film/film\tRoger Spottiswoode",
"Alaap\t/film/film\tHrishikesh Mukherjee",
"Achanak\t/film/film\tNaresh Malhotra",
"Asli Naqli\t/film/film\tHrishikesh Mukherjee",
"Alexander Nevsky\t/film/film\tD.I. Vassiliev",
"Dostana\t/film/film\tRaj Khosla",
"Himmat\t/film/film\tSunil Sharma",
"Jeet\t/film/film\tRaj Kanwar",
"Koshish\t/film/film\tGulzar",
"Mehndi\t/film/film\t",
"Mohra\t/film/film\tRajiv Rai",
"Nikaah\t/film/film\tB. R. Chopra",
"Ram Jaane\t/film/film\tRajiv Mehra",
"Menno\'s Mind\t/film/film\tJon Kroll",
"All About Ah-Long\t/film/film\tJohnny To",
"All About Eve\t/film/film\tJoseph L. Mankiewicz",
"All Quiet on the Western Front\t/film/film\tLewis Milestone",
"All the President\'s Men\t/film/film\tAlan J. Pakula",
"Altered States\t/film/film\tKen Russell",
"Alvarez Kelly\t/film/film\tEdward Dmytryk",
"Always\t/film/film\tSteven Spielberg",
"Amar Akbar Anthony\t/film/film\tManmohan Desai",
"The Big Brass Ring\t/film/film\tGeorge Hickenlooper",
"College\t/film/film\tJames W. Horne",
"Flash Gordon: Space Soldiers\t/film/film\tFrederick Stephani",
"The Saphead\t/film/film\tHerbert Blanche",
"Seven Chances\t/film/film\tBuster Keaton",
"American Flyers\t/film/film\tJohn Badham",
"An American in Paris\t/film/film\tVincente Minnelli",
"American Pop\t/film/film\tRalph Bakshi",
"The American President\t/film/film\tRob Reiner",
"Runaway Bride\t/film/film\tGarry Marshall",
"Andrei Rublev\t/film/film\tAndrei Tarkovsky",
"Angel and the Badman\t/film/film\tJames Edward Grant",
"Crazy in Alabama\t/film/film\tAntonio Banderas",
"The Story of Us\t/film/film\tRob Reiner",
"Grey Owl\t/film/film\tRichard Attenborough",
"One Man\'s Hero\t/film/film\tLance Hool",
"The Astronaut\'s Wife\t/film/film\tRand Ravich",
"The Muse\t/film/film\tAlbert Brooks",
"Aatish\t/film/film\tAmbarish Sangal",
"Annie Hall\t/film/film\tWoody Allen",
"The Wood\t/film/film\tRick Famuyiwa",
"Roti Kapada Aur Makaan\t/film/film\tManoj Kumar",
"Another Man\'s Poison\t/film/film\tIrving Rapper",
"B.U.S.T.E.D.\t/film/film\t",
"Annamalai\t/film/film\tSuresh Krishna",
"Seema\t/film/film\tAmiya Chakravarty",
"Dogma\t/film/film\tKevin Smith",
"All About My Mother\t/film/film\tPedro Almod\u00F3var",
"An Autumn\'s Tale\t/film/film\tMabel Cheung",
"Butch Cassidy and the Sundance Kid\t/film/film\tGeorge Roy Hill",
"Trick\t/film/film\tJim Fall",
"To Sir, with Love\t/film/film\tJames Clavell",
"As You Like It\t/film/film\tPaul Czinner",
"Jazz on a Summer\'s Day\t/film/film\tBert Stern",
"Godzilla vs. Destroyah / Godzilla vs. Space Godzilla Double Feature\t/film/film\tKensho Yamashita",
"Love and Death on Long Island\t/film/film\tRichard Kwietniowski",
"Richard III\t/film/film\tRichard Loncraine",
"Introducing Dorothy Dandridge\t/film/film\t",
"Assassins\t/film/film\tRichard Donner",
"187\t/film/film\tKevin Reynolds",
"Blood Feast\t/film/film\tHerschell Gordon Lewis",
"Color Me Blood Red\t/film/film\tHerschell Gordon Lewis",
"Emmanuelle 5\t/film/film\t",
"The Associate\t/film/film\tDonald Petrie",
"Best Laid Plans\t/film/film\t",
"Atomic Submarine\t/film/film\tSpencer Gordon Bennet",
"Autopsy\t/film/film\tArmando Crispino",
"Awakenings\t/film/film\tPenny Marshall",
"Bad Boys\t/film/film\tMichael Bay",
"Mann\t/film/film\tIndra Kumar",
"Boys Don\'t Cry\t/film/film\tKimberly Peirce",
"Music of the Heart\t/film/film\tWes Craven",
"Hillbillys in a Haunted House\t/film/film\tJean Yarbrough",
"Arunachalam\t/film/film\tC. Sundar",
"Retro Puppet Master\t/film/film\tDavid DeCoteau",
"The Trial\t/film/film\tOrson Welles",
"Who\'s Harry Crumb?\t/film/film\tPaul Flaherty",
"The Bone Collector\t/film/film\tPhillip Noyce",
"The Magical Legend of the Leprechauns\t/film/film\t",
"The Prophecy 3: The Ascent\t/film/film\tPatrick Lussier",
"Storm Riders\t/film/film\tAndrew Lau",
"Hot Boyz\t/film/film\tMaster P",
"Victor / Victoria\t/film/film\tBlake Edwards",
"Carnosaur 2\t/film/film\t",
"Three to Tango\t/film/film\tDamon Santostefano",
"The Bachelor\t/film/film\tGary Sinyor",
"End of Days\t/film/film\tPeter Hyams",
"The Audrey Hepburn Story\t/film/film\tSteve Robman",
"The Slipper and the Rose\t/film/film\tBryan Forbes",
"RKO 281\t/film/film\tBenjamin Ross",
"Ball of Fire\t/film/film\tHoward Hawks",
"La Bamba\t/film/film\tLuis Valdez",
"Baraka\t/film/film\tRon Fricke",
"Being John Malkovich\t/film/film\tSpike Jonze",
"Cradle Will Rock\t/film/film\tTim Robbins",
"Galaxy Quest\t/film/film\tDean Parisot",
"The Man with the Golden Gun\t/film/film\tGuy Hamilton",
"The World Is Not Enough\t/film/film\tMichael Apted",
"Barefoot in the Park\t/film/film\tGene Saks",
"Barsaat\t/film/film\tRaj Kumar Santoshi",
"Basic Instinct\t/film/film\tPaul Verhoeven",
"On Her Majesty\'s Secret Service\t/film/film\tPeter Hunt",
"Patita\t/film/film\tAmiya Chakravarthy",
"Princess Mononoke\t/film/film\tHayao Miyazaki",
"Best of the Best 3 & 4\t/film/film\tPhillip Rhee",
"Cleo from 5 to 7\t/film/film\tAgn\u00E8s Varda",
"Stuart Little\t/film/film\tRob Minkoff",
"Superstar\t/film/film\tBruce McCulloch",
"Fist of Legend\t/film/film\tGordon Chan",
"For Love of the Game\t/film/film\tSam Raimi",
"The Fox and the Hound\t/film/film\tRichard Rich",
"The Basketball Diaries\t/film/film\tScott Kalvert",
"Battling Butler\t/film/film\tBuster Keaton",
"The Bear\t/film/film\tJean-Jacques Annaud",
"Beavis and Butt-head Do America\t/film/film\tMike Judge",
"Bed of Roses\t/film/film\tMichael Goldenberg",
"Beethoven\'s 2nd\t/film/film\tRod Daniel",
"Before Sunrise\t/film/film\tRichard Linklater",
"Bell, Book and Candle\t/film/film\tRichard Quine",
"The Bells of St. Mary\'s\t/film/film\tLeo McCarey",
"Benji\t/film/film\tJoe Camp",
"Berlin: Symphony of a Great City / Opus 1\t/film/film\tWalter Ruttmann",
"The Best of Times\t/film/film\tRoger Spottiswoode",
"Big\t/film/film\tPenny Marshall",
"Big Bad Mama\t/film/film\tSteve Carver",
"Big Night\t/film/film\tStanley Tucci",
"The Big Trees\t/film/film\tFelix Feist",
"The Birdcage\t/film/film\tMike Nichols",
"Birdy\t/film/film\tAlan Parker",
"The Black Hole\t/film/film\tGary Nelson",
"The Black Pirate\t/film/film\tAlbert Parker",
"Black Rain\t/film/film\tRidley Scott",
"Blood on the Sun\t/film/film\tFrank Lloyd",
"Blown Away\t/film/film\tStephen Hopkins",
"The Blue Gardenia\t/film/film\tFritz Lang",
"Blue Thunder\t/film/film\tJohn Badham",
"Blue Velvet\t/film/film\tDavid Lynch",
"Body Snatchers\t/film/film\tAbel Ferrara",
"The Bodyguard\t/film/film\tMick Jackson",
"Boiling Point\t/film/film\tJames B. Harris",
"Born in East L.A.\t/film/film\tCheech Marin",
"Box of Moonlight\t/film/film\tTom DiCillo",
"The Boys from Brazil\t/film/film\tFranklin J. Schaffner",
"Boys on the Side\t/film/film\tHerbert Ross",
"The Brain That Wouldn\'t Die\t/film/film\tJoseph Green",
"Brainstorm\t/film/film\tDouglas Trumbull",
"Brassed Off\t/film/film\tMark Herman",
"Breakfast at Tiffany\'s\t/film/film\tBlake Edwards",
"The Breakfast Club\t/film/film\tJohn Hughes",
"Breathless\t/film/film\tJim McBride",
"Brewster\'s Millions\t/film/film\tWalter Hill",
"The Bridge at Remagen\t/film/film\tJohn Guillermin",
"The Bridge of San Luis Rey\t/film/film\tRowland V. Lee",
"The Bridges of Madison County\t/film/film\tClint Eastwood",
"The Brute Man\t/film/film\tJean Yarbrough",
"Swimming with Sharks\t/film/film\tGeorge Huang",
"Bull Durham\t/film/film\tRon Shelton",
"Bulletproof\t/film/film\tErnest R. Dickerson",
"Bullets Over Broadway\t/film/film\tWoody Allen",
"Bullitt\t/film/film\tPeter Yates",
"Burglar\t/film/film\tHugh Wilson",
"Bye Bye Birdie\t/film/film\tGeorge Sidney",
"Caligula\t/film/film\tTinto Brass",
"Camelot\t/film/film\tJoshua Logan",
"The Candidate\t/film/film\tMichael Ritchie",
"Cannibal Women in the Avocado Jungle of Death\t/film/film\tJ.D. Athens",
"The Cannonball Run II\t/film/film\tHal Needham",
"Career Opportunities\t/film/film\tBryan Gordon",
"Carlito\'s Way\t/film/film\tBrian De Palma",
"Carnosaur\t/film/film\t",
"The Cassandra Crossing\t/film/film\tGeorge P. Cosmatos",
"Castle Freak\t/film/film\tStuart Gordon",
"The Cat and the Canary\t/film/film\tPaul Leni",
"The Chamber\t/film/film\tJames Foley",
"Chances Are\t/film/film\tEmile Ardolino",
"Child\'s Play\t/film/film\tTom Holland",
"Child\'s Play 2: Chucky\'s Back\t/film/film\tJohn Lafia",
"The China Syndrome\t/film/film\tJames Bridges",
"Chinatown\t/film/film\tRoman Polanski",
"City Hunter\t/film/film\tJing Wong",
"The Clan of the Cave Bear\t/film/film\tMichael Chapman",
"National Lampoon\'s Class Reunion\t/film/film\tMichael Miller",
"Clean and Sober\t/film/film\tGlenn Gordon Caron",
"Clear and Present Danger\t/film/film\tPhillip Noyce",
"The Client\t/film/film\tJoel Schumacher",
"Cliffhanger\t/film/film\tRenny Harlin",
"Clockers\t/film/film\tSpike Lee",
"Clueless\t/film/film\tAmy Heckerling",
"Cobra\t/film/film\tGeorge P. Cosmatos",
"The Cocoanuts\t/film/film\tJoseph Santley",
"Coma\t/film/film\tMichael Crichton",
"Combat Shock\t/film/film\tBuddy Giovinazzo",
"Come and Get It\t/film/film\tHoward Hawks",
"Communion\t/film/film\tPhilippe Mora",
"Congo\t/film/film\tFrank Marshall",
"Cool Hand Luke\t/film/film\tStuart Rosenberg",
"Cooley High\t/film/film\tMichael Schultz",
"Copycat\t/film/film\tJon Amiel",
"Corridors of Blood\t/film/film\tRobert Day",
"Corrupt\t/film/film\tAlbert Pyun",
"The Court Jester\t/film/film\tNorman Panama",
"The Cowboy Way\t/film/film\tGregg Champion",
"The Cowboys\t/film/film\tMark Rydell",
"The Craft\t/film/film\tAndrew Fleming",
"Creator\t/film/film\tIvan Passer",
"Phenomena\t/film/film\tDario Argento",
"Creepshow\t/film/film\tGeorge A. Romero",
"Crimson Tide\t/film/film\tTony Scott",
"Crooklyn\t/film/film\tSpike Lee",
"The Crow: City of Angels\t/film/film\tTim Pope",
"The Crush\t/film/film\tAlan Shapiro",
"Cry Freedom\t/film/film\tRichard Attenborough",
"Cry Uncle\t/film/film\tJohn G. Avildsen",
"Cutthroat Island\t/film/film\tRenny Harlin",
"Cyborg\t/film/film\tAlbert Pyun",
"Daddy Long Legs\t/film/film\tMarshall Neilan",
"Dancing in the Dark\t/film/film\tBill Corcoran",
"Dangerous Liaisons\t/film/film\tStephen Frears",
"The Dark Crystal\t/film/film\tFrank Oz",
"The Dark Half\t/film/film\tGeorge A. Romero",
"Day of the Animals\t/film/film\tWilliam Girdler",
"The Day of the Jackal\t/film/film\tFred Zinnemann",
"Days of Thunder\t/film/film\tTony Scott",
"Dead Calm\t/film/film\tPhillip Noyce",
"Dead Man Walking\t/film/film\tTim Robbins",
"Dead Men Don\'t Wear Plaid\t/film/film\tCarl Reiner",
"Dead Presidents\t/film/film\tAlbert Hughes",
"Death Becomes Her\t/film/film\tRobert Zemeckis",
"Death Race 2000\t/film/film\tPaul Bartel",
"The Decameron\t/film/film\tPier Paolo Pasolini",
"Deep Cover\t/film/film\tBill Duke",
"Def by Temptation\t/film/film\tJames Bond III",
"Deliverance\t/film/film\tJohn Boorman",
"Demon City Shinjuku\t/film/film\t",
"Dentist\t/film/film\tBrian Yuzna",
"Destination Moon\t/film/film\tIrving Pichel",
"Devil Girl from Mars\t/film/film\tDavid MacDonald",
"Devil in a Blue Dress\t/film/film\tCarl Franklin",
"The Devil\'s Rain\t/film/film\tRobert Feust",
"The Dirty Dozen\t/film/film\tRobert Aldrich",
"Disclosure\t/film/film\tBarry Levinson",
"Dixiana\t/film/film\tLuther Reed",
"Dolores Claiborne\t/film/film\tTaylor Hackford",
"Don Juan De Marco\t/film/film\tJeremy Leven",
"Don\'s Party\t/film/film\tBruce Beresford",
"Don\'t Touch the White Woman!\t/film/film\tMarco Ferreri",
"The Doors\t/film/film\tOliver Stone",
"Dr. No\t/film/film\tTerence Young",
"Dracula\t/film/film\tJohn Badham",
"Dragnet\t/film/film\tTom Mankiewicz",
"Drive\t/film/film\tSteve Wang",
"Driving Miss Daisy\t/film/film\tBruce Beresford",
"Dune\t/film/film\tDavid Lynch",
"Eastern Condors\t/film/film\tSammo Hung Kam-Bo",
"Easy Rider\t/film/film\tDennis Hopper",
"Ebony, Ivory & Jade\t/film/film\tCirio H. Santiago",
"Eddie\t/film/film\tSteve Rash",
"The Eiger Sanction\t/film/film\tClint Eastwood",
"El Dorado\t/film/film\tHoward Hawks",
"The Electric Horseman\t/film/film\tSydney Pollack",
"Embrace of the Vampire\t/film/film\tAnne Goursaud",
"Embryo\t/film/film\t",
"The English Patient\t/film/film\tAnthony Minghella",
"The Englishman Who Went Up a Hill but Came Down a Mountain\t/film/film\tChristopher Monger",
"Eraser\t/film/film\tCharles Russell",
"Escape from Alcatraz\t/film/film\tDon Siegel",
"Escape from Sobibor\t/film/film\tJack Gold",
"The Exorcist 3\t/film/film\tWilliam Peter Blatty",
"Extreme Measures\t/film/film\tMichael Apted",
"Fahrenheit 451\t/film/film\tFran\u00E7ois Truffaut",
"Fair Game\t/film/film\tAndrew Sipes",
"Far and Away\t/film/film\tRon Howard",
"The Farmer\'s Wife\t/film/film\tAlfred Hitchcock",
"Father of the Bride\t/film/film\tCharles Shyer",
"Fear\t/film/film\tJames Foley",
"Fearless\t/film/film\tPeter Weir",
"Operation Condor\t/film/film\tJackie Chan",
"Ferris Bueller\'s Day Off\t/film/film\tJohn Hughes",
"A Few Good Men\t/film/film\tRob Reiner",
"Fiddler on the Roof\t/film/film\tNorman Jewison",
"Field of Dreams\t/film/film\tPhil Alden Robinson",
"The Fighting Seabees\t/film/film\tEdward Ludwig",
"The First Deadly Sin\t/film/film\tBrian Hutton",
"First Man Into Space\t/film/film\tRobert Day",
"The First Wives Club\t/film/film\tHugh Wilson",
"A Fish Called Wanda\t/film/film\tCharles Crichton",
"Fist of Fear, Touch of Death\t/film/film\tMatthew Mallinson",
"The Flamingo Kid\t/film/film\tGarry Marshall",
"Flash Gordon\t/film/film\tMike Hodges",
"Flatliners\t/film/film\tJoel Schumacher",
"The Flintstones\t/film/film\tBrian Levant",
"For Whom the Bell Tolls\t/film/film\tSam Wood",
"Forbidden Planet\t/film/film\tFred M. Wilcox",
"Force 10 from Navarone\t/film/film\tGuy Hamilton",
"Forever Young\t/film/film\tSteve Miner",
"Frankenhooker\t/film/film\tFrank Henenlotter",
"Free Willy\t/film/film\tSimon Wincer",
"Freeway\t/film/film\tMatthew Bright",
"French Kiss\t/film/film\tLawrence Kasdan",
"Fresh\t/film/film\tBoaz Yakin",
"Friday the 13th\t/film/film\tSean S. Cunningham",
"Friday the 13th: Part 2\t/film/film\tSteve Miner",
"Fried Green Tomatoes\t/film/film\tJon Avnet",
"Fright Night\t/film/film\tTom Holland",
"From Dusk Till Dawn\t/film/film\tRobert Rodriguez",
"From Russia With Love\t/film/film\tTerence Young",
"Full Metal Jacket\t/film/film\tStanley Kubrick",
"The Funhouse\t/film/film\tTobe Hooper",
"Funny Farm\t/film/film\tGeorge Roy Hill",
"A Funny Thing Happened on the Way to the Forum\t/film/film\tRichard Lester",
"Gallipoli\t/film/film\tPeter Weir",
"Ganja & Hess\t/film/film\tBill Gunn",
"The Gauntlet\t/film/film\tClint Eastwood",
"Gentleman\'s Agreement\t/film/film\tElia Kazan",
"Get Shorty\t/film/film\tBarry Sonnenfeld",
"The Getaway\t/film/film\tSam Peckinpah",
"The Getaway\t/film/film\tRoger Donaldson",
"Ghost Story\t/film/film\tJohn Irvin",
"Ghostbusters\t/film/film\tIvan Reitman",
"Ghostbusters 2\t/film/film\tIvan Reitman",
"Ghosts of Mississippi\t/film/film\tRob Reiner",
"The Girl Hunters\t/film/film\tRoy Rowland",
"The Glimmer Man\t/film/film\tJohn Gray",
"Glory\t/film/film\tEdward Zwick",
"Gold\t/film/film\tPeter Hunt",
"Gravesend\t/film/film\tSalvatore Stabile",
"Hard Times\t/film/film\tWalter Hill",
"The Great Santini\t/film/film\tLewis John Carlino",
"Groundhog Day\t/film/film\tHarold Ramis",
"Guarding Tess\t/film/film\tHugh Wilson",
"Blade\t/film/film\tStephen Norrington",
"Armageddon\t/film/film\tMichael Bay",
"Pleasantville\t/film/film\tGary Ross",
"Baby Geniuses\t/film/film\tBob Clark",
"The Red Violin\t/film/film\tFrancois Girard",
"Apt Pupil\t/film/film\tBryan Singer",
"Meet Joe Black\t/film/film\tMartin Brest",
"Eyes Wide Shut\t/film/film\tStanley Kubrick",
"U.S. Marshals\t/film/film\tStuart Bairo",
"The Mighty\t/film/film\tPeter Chelsom",
"The Horse Whisperer\t/film/film\tRobert Redford",
"Chairman of the Board\t/film/film\tAlex Zamm",
"Guys and Dolls\t/film/film\tJoseph L. Mankiewicz",
"Gypsy\t/film/film\tMervyn LeRoy",
"Hair\t/film/film\tMilos Forman",
"Half a Loaf of Kung Fu\t/film/film\tChi-Hwa Chen",
"Halloween\t/film/film\tJohn Carpenter",
"Halloween III: Season of the Witch\t/film/film\tTommy Lee Wallace",
"Halloween 4: The Return of Michael Myers\t/film/film\tDwight H. Little",
"Hamburger Hill\t/film/film\tJohn Irvin",
"Hang \'Em High\t/film/film\tTed Post",
"Happy Go Lovely\t/film/film\tH. Bruce Humberstone",
"Hard Target\t/film/film\tJohn Woo",
"Hard to Kill\t/film/film\tBruce Malmuth",
"The Hard Way\t/film/film\tJohn Badham",
"Havana\t/film/film\tSydney Pollack",
"The Heartbreak Kid\t/film/film\tElaine May",
"Heaven Can Wait\t/film/film\tWarren Beatty",
"Heaven\'s Gate\t/film/film\tMichael Cimino",
"Heavy\t/film/film\tJames Mangold",
"Henry & June\t/film/film\tPhilip Kaufman",
"Hero\t/film/film\tStephen Frears",
"The Hidden\t/film/film\tJack Sholder",
"High Noon\t/film/film\tFred Zinnemann",
"High Plains Drifter\t/film/film\tClint Eastwood",
"The Hindenburg\t/film/film\tRobert Wise",
"Hiroshima\t/film/film\tKoreyoshi Kurahara",
"History of the World: Part 1\t/film/film\tMel Brooks",
"Hocus Pocus\t/film/film\tKenny Ortega",
"Homeward Bound: The Incredible Journey\t/film/film\tDuwayne Dunham",
"Honeymoon in Vegas\t/film/film\tAndrew Bergman",
"Il Postino\t/film/film\tMichael Radford",
"The Breaks\t/film/film\tEric Meza",
"Our Town\t/film/film\tSam Wood",
"Bloodfist 2\t/film/film\tAndy Bluementhal",
"Bloodfist 4: Die Trying\t/film/film\tPaul Ziller",
"Perfect Blue\t/film/film\tSatoshi Kon",
"The End of the Affair\t/film/film\tNeil Jordan",
"Virtual Sexuality\t/film/film\tNick Hurran",
"Things Change\t/film/film\tDavid Mamet",
"The Guns of Navarone\t/film/film\tJ. Lee Thompson",
"Blue Hawaii\t/film/film\tNorman Taurog",
"Roustabout\t/film/film\tJohn Rich",
"The Endless Summer\t/film/film\tBruce Brown",
"The Gore Gore Girls: Special Edition\t/film/film\tHerschell Gordon Lewis",
"The Story of G.I. Joe\t/film/film\tWilliam A. Wellman",
"Visions of Light\t/film/film\tTodd McCarthy",
"Surf Crazy\t/film/film\t",
"Drowning Mona\t/film/film\tNick Gomez",
"The Next Best Thing\t/film/film\tJohn Schlesinger",
"The Whole Nine Yards\t/film/film\tJonathan Lynn",
"What Planet Are You From?\t/film/film\tMike Nichols",
"High Fidelity\t/film/film\tStephen Frears",
"The Road to El Dorado\t/film/film\tDon Paul",
"Rules of Engagement\t/film/film\tWilliam Friedkin",
"The Beach\t/film/film\tDanny Boyle",
"Sleepy Hollow\t/film/film\tTim Burton",
"The Talented Mr. Ripley\t/film/film\tAnthony Minghella",
"The Firm\t/film/film\tSydney Pollack",
"Drunken Master\t/film/film\tYuen Woo Ping",
"Good Times\t/film/film\tWilliam Friedkin",
"White Zombie\t/film/film\t",
"Desperately Seeking Susan\t/film/film\tSusan Seidelman",
"Married to the Mob\t/film/film\tJonathan Demme",
"F/X 2\t/film/film\tRichard Franklin",
"Missing in Action\t/film/film\tJoseph Zito",
"Switchblade Sisters\t/film/film\tJack Hill",
"Parting Glances\t/film/film\tBill Sherwood",
"The Architecture of Doom\t/film/film\tPeter Cohen",
"The Abyss\t/film/film\tJames Cameron",
"The Tempest\t/film/film\tDerek Jarman",
"The Ten Commandments\t/film/film\tCecil B. DeMille",
"The Omega Code\t/film/film\tRobert Marcarelli",
"Romeo is Bleeding\t/film/film\tPeter Medak",
"River\'s Edge\t/film/film\tTim Hunter",
"Pyaasa Sawan\t/film/film\tNarayana Rao Dasari",
"Baazi\t/film/film\tGuru Dutt",
"Aakraman\t/film/film\tJ. Om Prakash",
"Naya Daur\t/film/film\tB.R. Chopra",
"Ek Nai Paheli\t/film/film\tK. Balachander",
"Anmol\t/film/film\tKetan Desai",
"Final Destination\t/film/film\tJames Wong",
"Holy Smoke\t/film/film\tJane Campion",
"Rear Window\t/film/film\tAlfred Hitchcock",
"Paigham\t/film/film\t",
"Half Ticket\t/film/film\tKalidas",
"American Beauty\t/film/film\tSam Mendes",
"Snow Day\t/film/film\tChris Koch",
"The Cider House Rules\t/film/film\tLasse Hallstr\u00F6m",
"A Map of the World\t/film/film\tScott Elliott",
"Pitch Black\t/film/film\tDavid Twohy",
"3 Strikes\t/film/film\tD.J. Pooh",
"The Emperor and the Assassin\t/film/film\tKaige Chen",
"The Hurricane\t/film/film\tNorman Jewison",
"Dolphins: IMAX\t/film/film\tGreg MacGillivray",
"Any Given Sunday\t/film/film\tOliver Stone",
"Ghost Dog: The Way of the Samurai\t/film/film\tJim Jarmusch",
"Fantasia 2000\t/film/film\tGaetan Brizzi",
"Anna and the King\t/film/film\tAndy Tennant",
"The Third Miracle\t/film/film\tAgnieszka Holland",
"The War Zone\t/film/film\tTim Roth",
"Liberty Heights\t/film/film\tBarry Levinson",
"The Terrorist\t/film/film\tSantosh Sivan",
"The Life and Times of Hank Greenberg\t/film/film\tAviva Kempner",
"Rosetta\t/film/film\tLuc Dardenne",
"Kadosh\t/film/film\tAmos Gitai",
"Isn\'t She Great\t/film/film\tAndrew Bergman",
"Ride with the Devil\t/film/film\tAng Lee",
"All I Wanna Do\t/film/film\tSarah Kernochan",
"Man on the Moon\t/film/film\tMilos Forman",
"Love 101\t/film/film\tAdrian Fulle",
"My Best Fiend: Klaus Kinski\t/film/film\tWerner Herzog",
"Man of the Century\t/film/film\tAdam Abraham",
"Cosmic Voyage: IMAX\t/film/film\tBayley Silleck",
"The Dream Is Alive: IMAX\t/film/film\tGraeme Ferguson",
"Planet of the Apes\t/film/film\tFranklin J. Schaffner",
"Braveheart\t/film/film\tMel Gibson",
"North by Northwest\t/film/film\tAlfred Hitchcock",
"Please Not Now!\t/film/film\tRoger Vadim",
"The Goonies\t/film/film\tRichard Donner",
"Grease\t/film/film\tRandal Kleiser",
"Speaking in Strings: Nadja Salerno-Sonnenberg\t/film/film\tPaola Di Florio",
"Harold and Maude\t/film/film\tHal Ashby",
"Citizen Kane\t/film/film\tOrson Welles",
"The Filth and the Fury: A Sex Pistols Film\t/film/film\tJulien Temple",
"Dark Passage\t/film/film\tDelmer Daves",
"Fireworks\t/film/film\t\"Takeshi \"\"Beat\"\" Kitano\"",
"Safe\t/film/film\tTodd Haynes",
"Chungking Express\t/film/film\tKar Wai Wong",
"Sonatine\t/film/film\t\"Takeshi \"\"Beat\"\" Kitano\"",
"Spectres of the Spectrum\t/film/film\tCraig Baldwin",
"The Duke\t/film/film\tPhilip Spink",
"Contempt\t/film/film\tJean-Luc Godard",
"Live Flesh\t/film/film\tPedro Almod\u00F3var",
"Pandora\'s Box\t/film/film\tGeorg Wilhelm Pabst",
"Destiny\t/film/film\tFritz Lang",
"Mississippi Mermaid\t/film/film\tFran\u00E7ois Truffaut",
"Julien Donkey-Boy\t/film/film\tHarmony Korine",
"Simpatico\t/film/film\tMatthew Warchus",
"Beau Travail\t/film/film\tClaire Denis",
"The Last September\t/film/film\tDeborah Warner",
"Delicatessen\t/film/film\tJean-Pierre Jeunet",
"Mother Kusters Goes to Heaven\t/film/film\tRainer Werner Fassbinder",
"On the Waterfront\t/film/film\tElia Kazan",
"Playtime\t/film/film\tJacques Tati",
"The Skulls\t/film/film\tRob Cohen",
"Phir Bhi Dil Hai Hindustani\t/film/film\tAziz Mirza",
"Forrest Gump\t/film/film\tRobert Zemeckis",
"Bill & Ted\'s Excellent Adventure\t/film/film\tStephen Herek"].join('\n');