var complexData = 
["/type/object/type\t/type/object/name\t/film/film/initial_release_date\t/film/film/directed_by\t/film/film/starring:/film/performance/actor\t/film/film/starring:/film/performance/character", 
"/film/film\t¡Three Amigos!\t1986-12-12\tJohn Landis\tChevy Chase\tDusty Bottoms", 
"\t\t\t\tSteve Martin\tLucky Day", 
"\t\t\t\tMartin Short\tNed Nederlander", 
"\t\t\t\tJoe Mantegna\t", 
"\t\t\t\tJon Lovitz\tMorty", 
"\t\t\t\tPhil Hartman\t", 
"/film/film\t¿Quién es el señor López?\t2006-02\tLuis Mandoki\t\t", 
"/film/film\t...And Justice for All\t1979-06-29\tNorman Jewison\tAl Pacino\tArthur Kirkland", 
"\t\t\t\tJack Warden\t", 
"\t\t\t\tJohn Forsythe\t", 
"\t\t\t\tLee Strasberg\t", 
"\t\t\t\tThomas G. Waites\t", 
"\t\t\t\tDominic Chianese\t", 
"/film/film\tWhat Have I Done To Deserve This?\t1984-10-25\tPedro Almodóvar\tCarmen Maura\t", 
"\t\t\t\tLuis Hostalot\t", 
"\t\t\t\tVeronica Forqué\t", 
"/film/film\t*batteries not included\t1987-12-18\tMatthew Robbins\tHume Cronyn\t", 
"\t\t\t\tJessica Tandy\t", 
"\t\t\t\tFrank McRae\t", 
"\t\t\t\tElizabeth Peña\t", 
"\t\t\t\tMichael Carmine\t", 
"\t\t\t\tDennis Boutsikaris\t", 
"/film/film\t\"\"\"Weird Al\"\" Yankovic: The Ultimate Collection\"\t1993\tFrancis Delia\t\"\"\"Weird Al\"\" Yankovic\"\t", 
"\t\t\tJay Levey\t\t", 
"\t\t\tScott Norlund\t\t", 
"\t\t\tMark Osborne\t\t", 
"\t\t\tDror Soref\t\t", 
"\t\t\tRobert K. Weiss\t\t", 
"/film/film\t\"\"\"Manos\"\": The Hands of Fate\"\t1966-11-15\tHal Warren\tHal Warren\tMichael", 
"\t\t\t\tTom Neyman\tThe Master", 
"\t\t\t\tJohn Reynolds\tTorgo", 
"/film/film\t\"\"\"Weird Al\"\" Yankovic Live!\"\t1999-11-23\tMichael Dimich\t\"\"\"Weird Al\"\" Yankovic\"\t", 
"/film/film\t\"\"\"Weird Al\"\" Yankovic: The Ultimate Video Collection\"\t2003-11-04\tJay Levey\t\"\"\"Weird Al\"\" Yankovic\"\t", 
"\t\t\t\"\"\"Weird Al\"\" Yankovic\"\t\t", 
"/film/film\t\"\"\"Weird Al\"\" Yankovic: The Videos\"\t1998-01\tFrancis Delia\t\"\"\"Weird Al\"\" Yankovic\"\t", 
"\t\t\tJay Levey\t\t", 
"\t\t\tScott Norlund\t\t", 
"\t\t\tMark Osborne\t\t", 
"\t\t\tDror Soref\t\t", 
"\t\t\tRobert K. Weiss\t\t", 
"/film/film\t16 Vayathinile\t1977\tBharathiraja\tKamal Haasan\t", 
"\t\t\t\tRajnikanth\t", 
"\t\t\t\tSridevi Kapoor\t", 
"\t\t\t\tKantimathi\t", 
"/film/film\t15, Park Avenue\t2005\tAparna Sen\tKonkona Sen Sharma\t", 
"\t\t\t\tShabana Azmi\t", 
"\t\t\t\tSoumitra Chatterjee\t", 
"\t\t\t\tWaheeda Rehman\t", 
"\t\t\t\tDhritiman Chatterjee\t", 
"\t\t\t\tRahul Bose\t", 
"/film/film\t20 Million Miles to Earth\t1957\tNathan Juran\tWilliam Hopper\t", 
"\t\t\t\tJoan Taylor\t", 
"\t\t\t\tFrank Puglia\t", 
"/film/film\t36 Hours\t1965\tGeorge Seaton\tJames Garner\t", 
"\t\t\t\tRod Taylor\t", 
"\t\t\t\tEva Marie Saint\t", 
"/film/film\t2 Fast 2 Furious\t2003-06-06\tJohn Singleton\tPaul Walker\t", 
"\t\t\t\tTyrese\t", 
"\t\t\t\tEva Mendes\tMonica Fuentes", 
"\t\t\t\tLudacris\t", 
"\t\t\t\tDevon Aoki\t", 
"\t\t\t\tJames Remar\t", 
"/film/film\t99 River Street\t1953-10-02\tPhil Karlson\tJohn Payne\t", 
"\t\t\t\tEvelyn Keyes\t", 
"\t\t\t\tBrad Dexter\t", 
"\t\t\t\tFrank Faylen\t", 
"\t\t\t\tPeggie Castle\t", 
"/film/film\t37°2 le matin\t1986-11-07\tJean-Jacques Beineix\tJean-Hugues Anglade\tZorg", 
"\t\t\t\tBéatrice Dalle\tBetty", 
"\t\t\t\tVincent Lindon\t", 
"\t\t\t\tDominique Pinon\t", 
"/film/film\t8mm\t1999-02-26\tJoel Schumacher\tNicolas Cage\tTom Welles", 
"\t\t\t\tJoaquin Phoenix\tMax California", 
"\t\t\t\tJames Gandolfini\t", 
"\t\t\t\tCatherine Keener\t", 
"\t\t\t\tNorman Reedus\t", 
"\t\t\t\tPeter Stormare\t", 
"/film/film\t5 Card Stud\t1968\tHenry Hathaway\tDean Martin\t", 
"\t\t\t\tRobert Mitchum\t", 
"\t\t\t\tInger Stevens\t", 
"\t\t\t\tYaphet Kotto\t", 
"/film/film\t10 Rillington Place\t1971-05-12\tRichard Fleischer\tRichard Attenborough\t", 
"\t\t\t\tJudy Geeson\t", 
"\t\t\t\tJohn Hurt\t", 
"/film/film\t7G Rainbow Colony\t2005-10-15\tSelvaraghavan\tRavi Krishna\t", 
"\t\t\t\tSonia Agarwal\t", 
"\t\t\t\tO. V. Vijayan\t", 
"\t\t\t\tSuman Shetty\t", 
"/film/film\t3-Iron\t2004\tKim Ki-duk\tHyun-kyoon Lee\t", 
"\t\t\t\tJae Hee\t", 
"\t\t\t\tLee Seung-yeon\t", 
"/film/film\t11 Harrowhouse\t1974\t\tCharles Grodin\t", 
"\t\t\t\tCandice Bergen\t", 
"\t\t\t\tJames Mason\t", 
"/film/film\t3:10 to Yuma\t1957-08-07\tDelmer Daves\tGlenn Ford\tBen Wade", 
"\t\t\t\tVan Heflin\tDan Evans", 
"/film/film\t20,000 Leagues Under the Sea\t1954-12-23\tRichard Fleischer\tKirk Douglas\t", 
"\t\t\t\tJames Mason\t", 
"\t\t\t\tPaul Lukas\t", 
"\t\t\t\tPeter Lorre\t", 
"\t\t\t\tCarleton Young\t", 
"/film/film\t2010: The Year We Make Contact\t1984-12-07\tPeter Hyams\tRoy Scheider\tHeywood R. Floyd", 
"\t\t\t\tJohn Lithgow\tWalter Curnow", 
"\t\t\t\tHelen Mirren\tTanya Kirbuk", 
"\t\t\t\tBob Balaban\tDr. Chandra", 
"\t\t\t\tKeir Dullea\tDavid Bowman", 
"\t\t\t\tDouglas Rain\tHAL 9000", 
"/film/film\t10.5: Apocalypse\t2006-05-21\tJohn Lafia\tKim Delaney\t", 
"\t\t\t\tDavid Cubitt\t", 
"\t\t\t\tDean Cain\t", 
"\t\t\t\tCarlos Bernard\t", 
"\t\t\t\tFrank Langella\t", 
"\t\t\t\tBeau Bridges\t", 
"/film/film\t8 Mile\t2002-11-08\tCurtis Hanson\tEminem\t", 
"\t\t\t\tKim Basinger\t", 
"\t\t\t\tMekhi Phifer\t", 
"\t\t\t\tBrittany Murphy\t", 
"\t\t\t\tChloe Greenfield\t", 
"\t\t\t\tAnthony Mackie\t", 
"/film/film\t681 AD: The Glory of Khan\t1981\tLyudmil Staykov\tStoyko Peev\t", 
"\t\t\t\tAntoniy Genov\t", 
"\t\t\t\tVanya Tsvetkova\t", 
"\t\t\t\tĐoko Rosić\t", 
"\t\t\t\tAnya Pencheva\t", 
"\t\t\t\tPetar Slabakov\t", 
"/film/film\t100 Girls\t2001-09-25\tMichael Davis\tJonathan Tucker\t", 
"\t\t\tMichael Davis\tEmmanuelle Chriqui\t", 
"\t\t\t\tJames DeBello\t", 
"\t\t\t\tKatherine Heigl\tArlene", 
"\t\t\t\tLarisa Oleynik\t", 
"\t\t\t\tJaime Pressly\t", 
"/film/film\t40 Days and 40 Nights\t2002-03-01\tMichael Lehmann\tJosh Hartnett\t", 
"\t\t\t\tShannyn Sossamon\t", 
"\t\t\t\tTerry Chen\t", 
"\t\t\t\tMaggie Gyllenhaal\t", 
"\t\t\t\tMonet Mazur\t", 
"\t\t\t\tBarry Newman\t", 
"/film/film\t50 Cent: The New Breed\t2003-04-15\tDon Robinson\t50 Cent\t", 
"\t\t\tDamon Johnson\tEminem\t", 
"\t\t\t\tDr. Dre\t", 
"\t\t\t\tLloyd Banks\t", 
"\t\t\t\tTony Yayo\t", 
"/film/film\t3: The Dale Earnhardt Story\t2004-12-11\tRussell Mulcahy\tBarry Pepper\t", 
"\t\t\t\tElizabeth Mitchell\t", 
"\t\t\t\tChad McCumbee\tJunior", 
"/film/film\t200 Motels\t1971-11-10\tTony Palmer\t\t", 
"\t\t\tFrank Zappa\t\t", 
"\t\t\tCharles Swenson\t\t", 
"\t\t\tGillian Lynne\t\t", 
"/film/film\t61*\t2001-04-28\tBilly Crystal\tThomas Jane\t", 
"\t\t\t\tBarry Pepper\t", 
"\t\t\t\tBob Gunton\t", 
"\t\t\t\tJoe Grifasi\t", 
"\t\t\t\tMichael Nouri\t", 
"\t\t\t\tChristopher McDonald\t", 
"/film/film\t24 Hour Party People\t2002-04-05\tMichael Winterbottom\tJohn Simm\tBernard Sumner", 
"\t\t\t\tSteve Coogan\tTony Wilson", 
"\t\t\t\tShirley Henderson\tLindsay Wilson", 
"\t\t\t\tPaddy Considine\tRob Gretton", 
"\t\t\t\tChristopher Eccleston\t", 
"\t\t\t\tAndy Serkis\t", 
"/film/film\t8 Million Ways to Die\t1986-04-25\tHal Ashby\tJeff Bridges\t", 
"\t\t\t\tRandy Brooks\t", 
"\t\t\t\tAlexandra Paul\t", 
"/film/film\t10th & Wolf\t2006-08-18\tRobert Moresco\tJames Marsden\tTommy", 
"\t\t\t\tGiovanni Ribisi\t", 
"\t\t\t\tBrad Renfro\t", 
"\t\t\t\tBrian Dennehy\t", 
"\t\t\t\tLesley Ann Warren\t", 
"\t\t\t\tDash Mihok\t", 
"/film/film\t25th Hour\t2003\tSpike Lee\tEdward Norton\t", 
"\t\t\t\tPhilip Seymour Hoffman\t", 
"\t\t\t\tBarry Pepper\t", 
"\t\t\t\tRosario Dawson\t", 
"\t\t\t\tBrian Cox\t", 
"\t\t\t\tAnna Paquin\t", 
"/film/film\t02:37:00 AM\t2006-08-17\tMurali K. Thalluri\tFrank Sweet\t", 
"\t\t\t\tJoel Mackenzie\t", 
"\t\t\t\tTeresa Palmer\t", 
"\t\t\t\tMarni Spillane\t", 
"\t\t\t\tGary Sweet\t", 
"\t\t\t\tCharles Baird\t", 
"/film/film\t48 Hrs.\t1982-12-08\tWalter Hill\tNick Nolte\t", 
"\t\t\t\tEddie Murphy\t", 
"\t\t\t\tAnnette O'Toole\t", 
"\t\t\t\tFrank McRae\t", 
"\t\t\t\tJames Remar\t", 
"\t\t\t\tDavid Patrick Kelly\tLuther", 
"/film/film\t7 Seconds\t2005-06-28\tSimon Fellows\tWesley Snipes\t", 
"\t\t\t\tTamzin Outhwaite\t", 
"/film/film\t28 Days Later\t2002-11-01\tDanny Boyle\tCillian Murphy\t", 
"\t\t\t\tNaomie Harris\t", 
"\t\t\t\tBrendan Gleeson\t", 
"\t\t\t\tChristopher Eccleston\t", 
"\t\t\t\tMegan Burns\t", 
"\t\t\t\tLuke Mably\t", 
"/film/film\t21 Grams\t2003-09-05\tAlejandro González Iñárritu\tSean Penn\t", 
"\t\t\t\tNaomi Watts\tCristina Peck", 
"\t\t\t\tBenicio del Toro\t"].join("\n");