var sampleData = ["/type/object/name\t/type/object/type\t/film/film/directed_by",
"Stolen Kisses\t/film/film\tFran\u00E7ois Truffaut",
"The Stoned Age\t/film/film\tJames Melkonian",
"Stonewall\t/film/film\tNigel Finch",
"Strange Days\t/film/film\tKathryn Bigelow",
"The Strange Love of Martha Ivers\t/film/film\tLewis Milestone",
"Straw Dogs\t/film/film\tSam Peckinpah",
"A Streetcar Named Desire\t/film/film\tElia Kazan",
"Stripes\t/film/film\tIvan Reitman",
"Stroker Ace\t/film/film\tHal Needham",
"Summertime\t/film/film\tDavid Lean",
"Sunday in the Country\t/film/film\tBertrand Tavernier",
"Surviving the Game\t/film/film\tErnest R. Dickerson",
"Swashbuckler\t/film/film\tJames Goldstone",
"Sweet Dreams\t/film/film\tKarel Reisz",
"Swingers\t/film/film\tDoug Liman",
"Hard Eight\t/film/film\tPaul Thomas Anderson",
"Take the Money and Run\t/film/film\tWoody Allen",
"Tale of Two Sisters\t/film/film\tAdam Rifkin",
"Tales from the Crypt: Demon Knight\t/film/film\tErnest R. Dickerson",
"Tampopo\t/film/film\tJuzo Itami",
"Tango & Cash\t/film/film\tAndrei Konchalovsky",
"Tequila Sunrise\t/film/film\tRobert Towne",
"The Terminator\t/film/film\tJames Cameron",
"Terror of Mechagodzilla\t/film/film\tIshir\u00F4 Honda",
"Tess of the Storm Country\t/film/film\tJohn S. Robertson",
"Tetsuo 2: Body Hammer\t/film/film\tShinya Tsukamoto",
"Tetsuo: The Iron Man\t/film/film\tShinya Tsukamoto",
"They Might Be Giants\t/film/film\tAnthony Harvey",
"The Thief of Bagdad\t/film/film\tRaoul Walsh",
"The Thing\t/film/film\tJohn Carpenter",
"Things to Do in Denver When You\'re Dead\t/film/film\tGary Fleder",
"This Sporting Life\t/film/film\tLindsay Anderson",
"The Thomas Crown Affair\t/film/film\tNorman Jewison",
"Three Amigos\t/film/film\tJohn Landis",
"Three Days of the Condor\t/film/film\tSydney Pollack",
"The Three Musketeers\t/film/film\tStephen Herek",
"Thunder Road\t/film/film\tRobert Mitchum",
"Thunderball\t/film/film\tTerence Young",
"Thunderheart\t/film/film\tMichael Apted",
"Tiger Bay\t/film/film\tJ. Lee Thompson",
"Tim\t/film/film\tMichael Pate",
"Timecop\t/film/film\tPeter Hyams",
"Tin Cup\t/film/film\tRon Shelton",
"The Tingler\t/film/film\tWilliam Castle",
"To Die For\t/film/film\tGus Van Sant",
"Tokyo Fist\t/film/film\tShinya Tsukamoto",
"Tol\'able David\t/film/film\tHenry King",
"Tora! Tora! Tora!\t/film/film\tKinji Fukasuka",
"Tornado!\t/film/film\tNoel Nosseck"].join('\n');